name: JUnit Testing

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Make Gradlew executable
      run: chmod +x gradlew
      working-directory: lab2

    - name: Build with Gradle
      working-directory: lab2
      run: ./gradlew build

    - name: Run Tests
      working-directory: lab2
      run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deployment
        run: echo "Deployment completed successfully!"